### PR TITLE
Master

### PR DESCRIPTION
**Pull request by EthChil**

### CODE REVIEW

**Comment by karenkozma** [comment]
Hi Jamie 
What are all of these programming lessons being closed? Is it the earlier material we were working on?

Karen Kozma

**Comment by JamieSinn** [comment]
This is just some old material we worked on in November/December.

**Comment by karenkozma** [comment]
thought so - thanks for tying up loose ends - by the way, your suggestion of giving back to the community was very good.
take care and thank you
Dr. Kozma

**Comment by JamieSinn** [comment]
Thanks!

**Pull request closed without merging**
